input_train_data_path: "data/train_data.csv"
input_test_data_path: "data/test_data.csv"
scaler_path: "model/scaler.joblib"
model_path: "model/model.pkl"
predict_path: "data/predict.csv"
model_type: "LogisticRegression"
features:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "ca"
  target_col: "condition"
splitting_params:
  val_size: 0.1
  random_state: 3
  stratify: True
