input_data_path: "data/heart_cleveland_upload.csv"
output_scaler_path: "model/scaler.joblib"
output_model_path: "model/model.pkl"
features:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
    - "ca"
  target_col: "condition"